aft_seq_length: 1
batch_size: 16
dropout: 0.0
epochs: 50
hidden_dim: 256
kernel_size:
- 5
- 5
lr: 2.00e-05
num_layers: 3
pre_seq_length: 20
weight_decay: 0.001
feature_cols:
  - pet
  - pre
  - tmx
  - tmn
  - tmp
  - cld
  - dmi
  - soi
  - nino3
  - nino4
  - nino34
  - pdo
  - dtr
  - wet
  - vap
  - spei

target_cols: 
  - spei

lat_key: lat
lon_key: lon
time_key: time

spatial_dim:
  - 30
  - 17

scale_range: [-1, 1]